export interface CountryOption {
  code: string;
  label: string;
  gl: string;
  hl: string;
}

export const COUNTRIES: CountryOption[] = [
  { code: "id", label: "Indonesia", gl: "id", hl: "id" },
  { code: "my", label: "Malaysia", gl: "my", hl: "ms" },
  { code: "sg", label: "Singapura", gl: "sg", hl: "en" },
  { code: "ph", label: "Filipina", gl: "ph", hl: "en" },
  { code: "th", label: "Thailand", gl: "th", hl: "th" },
  { code: "vn", label: "Vietnam", gl: "vn", hl: "vi" },
  { code: "in", label: "India", gl: "in", hl: "en" },
  { code: "pk", label: "Pakistan", gl: "pk", hl: "en" },
  { code: "bd", label: "Bangladesh", gl: "bd", hl: "bn" },
  { code: "lk", label: "Sri Lanka", gl: "lk", hl: "en" },
  { code: "mm", label: "Myanmar", gl: "mm", hl: "en" },
  { code: "kh", label: "Kamboja", gl: "kh", hl: "en" },
  { code: "la", label: "Laos", gl: "la", hl: "en" },
  { code: "bn", label: "Brunei", gl: "bn", hl: "ms" },
  { code: "np", label: "Nepal", gl: "np", hl: "en" },
  { code: "jp", label: "Jepang", gl: "jp", hl: "ja" },
  { code: "kr", label: "Korea Selatan", gl: "kr", hl: "ko" },
  { code: "cn", label: "Tiongkok", gl: "cn", hl: "zh-cn" },
  { code: "hk", label: "Hong Kong", gl: "hk", hl: "zh-tw" },
  { code: "tw", label: "Taiwan", gl: "tw", hl: "zh-tw" },
  { code: "mn", label: "Mongolia", gl: "mn", hl: "en" },
  { code: "us", label: "Amerika Serikat", gl: "us", hl: "en" },
  { code: "ca", label: "Kanada", gl: "ca", hl: "en" },
  { code: "mx", label: "Meksiko", gl: "mx", hl: "es" },
  { code: "br", label: "Brasil", gl: "br", hl: "pt-br" },
  { code: "ar", label: "Argentina", gl: "ar", hl: "es" },
  { code: "cl", label: "Chili", gl: "cl", hl: "es" },
  { code: "co", label: "Kolombia", gl: "co", hl: "es" },
  { code: "pe", label: "Peru", gl: "pe", hl: "es" },
  { code: "gb", label: "Inggris (UK)", gl: "gb", hl: "en" },
  { code: "ie", label: "Irlandia", gl: "ie", hl: "en" },
  { code: "de", label: "Jerman", gl: "de", hl: "de" },
  { code: "fr", label: "Prancis", gl: "fr", hl: "fr" },
  { code: "es", label: "Spanyol", gl: "es", hl: "es" },
  { code: "it", label: "Italia", gl: "it", hl: "it" },
  { code: "pt", label: "Portugal", gl: "pt", hl: "pt-pt" },
  { code: "nl", label: "Belanda", gl: "nl", hl: "nl" },
  { code: "be", label: "Belgia", gl: "be", hl: "nl" },
  { code: "ch", label: "Swiss", gl: "ch", hl: "de" },
  { code: "at", label: "Austria", gl: "at", hl: "de" },
  { code: "se", label: "Swedia", gl: "se", hl: "sv" },
  { code: "no", label: "Norwegia", gl: "no", hl: "no" },
  { code: "dk", label: "Denmark", gl: "dk", hl: "da" },
  { code: "fi", label: "Finlandia", gl: "fi", hl: "fi" },
  { code: "pl", label: "Polandia", gl: "pl", hl: "pl" },
  { code: "cz", label: "Republik Ceko", gl: "cz", hl: "cs" },
  { code: "gr", label: "Yunani", gl: "gr", hl: "el" },
  { code: "ro", label: "Rumania", gl: "ro", hl: "ro" },
  { code: "hu", label: "Hungaria", gl: "hu", hl: "hu" },
  { code: "ua", label: "Ukraina", gl: "ua", hl: "uk" },
  { code: "ru", label: "Rusia", gl: "ru", hl: "ru" },
  { code: "tr", label: "Turki", gl: "tr", hl: "tr" },
  { code: "ae", label: "Uni Emirat Arab", gl: "ae", hl: "ar" },
  { code: "sa", label: "Arab Saudi", gl: "sa", hl: "ar" },
  { code: "qa", label: "Qatar", gl: "qa", hl: "ar" },
  { code: "kw", label: "Kuwait", gl: "kw", hl: "ar" },
  { code: "eg", label: "Mesir", gl: "eg", hl: "ar" },
  { code: "il", label: "Israel", gl: "il", hl: "he" },
  { code: "za", label: "Afrika Selatan", gl: "za", hl: "en" },
  { code: "ng", label: "Nigeria", gl: "ng", hl: "en" },
  { code: "ke", label: "Kenya", gl: "ke", hl: "en" },
  { code: "au", label: "Australia", gl: "au", hl: "en" },
  { code: "nz", label: "Selandia Baru", gl: "nz", hl: "en" },
];

export function getCountry(code?: string | null): CountryOption {
  return COUNTRIES.find((c) => c.code === code) ?? COUNTRIES[0];
}
