// Shared between the Live TikTok voice picker (client) and the Google Cloud TTS
// server helpers — kept in its own module (no server-only imports) so the
// client bundle can import it directly. Mirrors elevenlabs-languages.ts.

// Every locale Chirp3 HD actually has voices for on this account, confirmed
// live against the real Text-to-Speech API (client.listVoices) rather than
// guessed — Chirp3 HD's lineup has changed shape before, but a full account
// audit is a reasonable point-in-time source for which locales are worth
// exposing in this picker.
export const GOOGLE_TTS_LANGUAGES = [
  { code: "id-ID", label: "Indonesia" },
  { code: "en-US", label: "Inggris (AS)" },
  { code: "en-GB", label: "Inggris (Inggris)" },
  { code: "en-AU", label: "Inggris (Australia)" },
  { code: "en-IN", label: "Inggris (India)" },
  { code: "cmn-CN", label: "Mandarin" },
  { code: "yue-HK", label: "Kanton (Hong Kong)" },
  { code: "ja-JP", label: "Jepang" },
  { code: "ko-KR", label: "Korea" },
  { code: "vi-VN", label: "Vietnam" },
  { code: "th-TH", label: "Thailand" },
  { code: "hi-IN", label: "Hindi" },
  { code: "bn-IN", label: "Bengali" },
  { code: "ta-IN", label: "Tamil" },
  { code: "te-IN", label: "Telugu" },
  { code: "mr-IN", label: "Marathi" },
  { code: "kn-IN", label: "Kannada" },
  { code: "ml-IN", label: "Malayalam" },
  { code: "gu-IN", label: "Gujarati" },
  { code: "pa-IN", label: "Punjabi" },
  { code: "ur-IN", label: "Urdu" },
  { code: "ar-XA", label: "Arab" },
  { code: "he-IL", label: "Ibrani" },
  { code: "tr-TR", label: "Turki" },
  { code: "sw-KE", label: "Swahili" },
  { code: "es-ES", label: "Spanyol (Spanyol)" },
  { code: "es-US", label: "Spanyol (AS)" },
  { code: "pt-BR", label: "Portugis (Brasil)" },
  { code: "fr-FR", label: "Prancis (Prancis)" },
  { code: "fr-CA", label: "Prancis (Kanada)" },
  { code: "de-DE", label: "Jerman" },
  { code: "it-IT", label: "Italia" },
  { code: "nl-NL", label: "Belanda (Belanda)" },
  { code: "nl-BE", label: "Belanda (Belgia)" },
  { code: "pl-PL", label: "Polandia" },
  { code: "sv-SE", label: "Swedia" },
  { code: "da-DK", label: "Denmark" },
  { code: "fi-FI", label: "Finlandia" },
  { code: "nb-NO", label: "Norwegia" },
  { code: "el-GR", label: "Yunani" },
  { code: "cs-CZ", label: "Ceko" },
  { code: "sk-SK", label: "Slovakia" },
  { code: "hu-HU", label: "Hungaria" },
  { code: "ro-RO", label: "Rumania" },
  { code: "bg-BG", label: "Bulgaria" },
  { code: "hr-HR", label: "Kroasia" },
  { code: "sr-RS", label: "Serbia" },
  { code: "sl-SI", label: "Slovenia" },
  { code: "et-EE", label: "Estonia" },
  { code: "lv-LV", label: "Latvia" },
  { code: "lt-LT", label: "Lituania" },
  { code: "uk-UA", label: "Ukraina" },
  { code: "ru-RU", label: "Rusia" },
] as const;
