-- AlterTable
ALTER TABLE `generation` MODIFY `type` ENUM('SEO_KEYWORDS', 'SEO_META', 'SEO_ARTICLE', 'IMAGE_GENERATION', 'VIDEO_GENERATION') NOT NULL,
    MODIFY `status` ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED') NOT NULL DEFAULT 'COMPLETED';
