-- AlterTable
ALTER TABLE `generation` MODIFY `type` ENUM('SEO_KEYWORDS', 'SEO_META', 'SEO_ARTICLE', 'IMAGE_GENERATION', 'VIDEO_GENERATION', 'VOICE_DUB', 'TIKTOK_LIVE_REPLY', 'AVATAR_GENERATION') NOT NULL;
