-- AlterTable
ALTER TABLE `CreditTransaction` MODIFY `type` ENUM('TOPUP', 'USAGE', 'REFUND', 'BONUS', 'ADJUSTMENT') NOT NULL;

-- AlterTable
ALTER TABLE `User` ADD COLUMN `status` ENUM('ACTIVE', 'SUSPENDED') NOT NULL DEFAULT 'ACTIVE';

